version: 2
project_name: swerpicommerce-pp-cli
changelog:
  disable: true
builds:
  - id: swerpicommerce-pp-cli
    main: ./cmd/swerpicommerce-pp-cli
    binary: swerpicommerce-pp-cli
    env:
      - CGO_ENABLED=0
    ldflags:
      - -s -w -X swerpicommerce-pp-cli/internal/cli.version={{ .Version }}
    targets:
      - darwin_amd64
      - darwin_arm64
      - linux_amd64
      - linux_arm64
      - windows_amd64
      - windows_arm64
  - id: swerpicommerce-pp-mcp
    main: ./cmd/swerpicommerce-pp-mcp
    binary: swerpicommerce-pp-mcp
    env:
      - CGO_ENABLED=0
    ldflags:
      - -s -w
    targets:
      - darwin_amd64
      - darwin_arm64
      - linux_amd64
      - linux_arm64
      - windows_amd64
      - windows_arm64
archives:
  - formats: [tar.gz]
    name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    format_overrides:
      - goos: windows
        formats: [zip]
checksum:
  name_template: checksums.txt
brews:
  - name: swerpicommerce-pp-cli
    repository:
      owner: user
      name: homebrew-tap
    homepage: "https://github.com/user/swerpicommerce-pp-cli"
    description: "REST API v2 schema-first per la gestione di ordini, clienti, prodotti, pagine CMS e configurazioni e-commerce. Tutti..."
    install: |
      bin.install "swerpicommerce-pp-cli"
      bin.install "swerpicommerce-pp-mcp"
